# Each scene: title, layout, items (revealed progressively), sentences [(text, items_visible)]
SCENES = [
 dict(title="Can Boring Go Viral?", layout="hero",
  items=["No luck. No giant ad budget.", "Jonah Berger  |  Wharton  |  Author of Contagious"],
  sents=[
   ("Imagine turning a dull, everyday product into an internet sensation, on a shoestring budget.", 0),
   ("Most people assume that takes either luck, or a giant advertising budget.", 1),
   ("Today we look at a very different answer, from Wharton marketing professor Jonah Berger.", 2),
   ("His claim is simple. Going viral is not a lottery. It is a science, and it can be engineered.", 2),
   ("Stay with us, because the examples are surprising, and the lessons work for almost any product.", 2)]),
 dict(title="Today's Agenda", layout="bullets",
  items=["1. Why viral is not luck", "2. The six STEPPS triggers", "3. Real examples: KitKat, a blender, luxury chips", "4. How to do it on a tiny budget"],
  sents=[
   ("Jonah Berger has spent about twenty years studying why some ideas catch on while others disappear.", 0),
   ("He is the author of the book Contagious, and he has identified six psychological triggers that make people talk and share.", 0),
   ("First, we will look at why virality is not luck.", 1),
   ("Second, we will walk through the six triggers, known by the acronym STEPPS.", 2),
   ("Third, we will test them on real examples, from a chocolate bar to a kitchen blender to a bag of potato chips.", 3),
   ("And finally, we will look at how to apply all of this when your budget is close to zero.", 4)]),
 dict(title="Virality Is Science, Not Luck", layout="bullets",
  items=["People share for psychological reasons", "The patterns are predictable", "Social Currency: sharing makes us look good"],
  sents=[
   ("Most people think viral hits are random. Jonah disagrees.", 0),
   ("He found that people share things for psychological reasons, not because of chance.", 1),
   ("And if the reasons are predictable, then the results can be designed.", 2),
   ("Let us start with the first reason, which is called Social Currency.", 2),
   ("People share things that make them look good, or feel like insiders.", 3),
   ("Think about the last time you told a friend about a hidden restaurant, or a surprising fact. You were not doing them a favor. You were quietly showing that you know things.", 3),
   ("So if you give people an exclusive experience, or a cool story, they will happily bring it up for you.", 3)]),
 dict(title="Interesting Is Not Viral", layout="compare",
  items=["Interesting product, no hook|Little extra word of mouth", "Product with a trigger or story|People keep talking about it"],
  sents=[
   ("Here is a point that surprises many marketers.", 0),
   ("Jonah's research suggests that simply being interesting does not create extra word of mouth.", 1),
   ("A flashy product, a quirky label, even a celebrity endorsement, can all fall flat.", 1),
   ("Imagine an exciting new soda with a bold design. If nothing connects it to a daily cue, an emotion, or a story, people have no reason to bring it up.", 1),
   ("Now compare that with a product that is tied to something people already do, feel, or care about.", 2),
   ("That product gets mentioned again and again, without any extra push. The difference is the hook.", 2)]),
 dict(title="The STEPPS Framework", layout="steps",
  items=["Social Currency|Look good, feel special", "Triggers|Linked to everyday cues", "Emotion|High-arousal feelings", "Public|Visible and imitable", "Practical Value|Useful tips and deals", "Stories|Wrap the message in a tale"],
  sents=[
   ("Jonah's secret sauce is the STEPPS framework. Six drivers of sharing.", 0),
   ("S stands for Social Currency. People share what makes them look good.", 1),
   ("T stands for Triggers. Link your idea to cues that people meet often.", 2),
   ("E stands for Emotion. Feelings that get us fired up, like awe, excitement, or even outrage, make us share.", 3),
   ("P stands for Public. If people can see a product being used, it spreads. Things that are built to show, grow.", 4),
   ("The second P is Practical Value. People love passing on useful information and good deals.", 5),
   ("And the last S is Stories. Wrap your message inside a story, and people carry it for you.", 6),
   ("You do not need all six at once. But the more of them you use, the more contagious the idea becomes.", 6)]),
 dict(title="Triggers: KitKat Meets Coffee", layout="bullets",
  items=["Pair the product with a frequent cue", "Coffee break  ->  KitKat break", "The cue does the reminding for you"],
  sents=[
   ("Let us see triggers in action, with a chocolate bar.", 0),
   ("KitKat tied its brand to one of the most common moments in the day, the coffee break.", 1),
   ("Their ads paired the chocolate bar with coffee again and again.", 2),
   ("The result is that every time someone reaches for a coffee, a small reminder of KitKat pops up in their mind.", 2),
   ("And because that trigger shows up many times a day, the brand stays top of mind, with almost no extra advertising.", 3),
   ("This is why Jonah says the goal is not to go viral for its own sake. The goal is to be remembered, often, in the right moments.", 3)]),
 dict(title="Case Study: Will It Blend?", layout="stats",
  items=["$503|ad budget", "200M+|views", "+700%|sales"],
  sents=[
   ("Now to the case study everyone remembers. A blender.", 0),
   ("A small team made a video series called Will It Blend, where a blender chews up unexpected things, even a brand new phone.", 0),
   ("The episode cites a budget of just five hundred and three dollars.", 1),
   ("And the series reportedly passed two hundred million views, with sales rising by around seven hundred percent.", 3),
   ("Why did it work? Surprise and entertainment. Nobody wants to share an ad about blade sharpness.", 3),
   ("But everyone wants to share the moment a phone turns into dust. That is Emotion and Public working together.", 3),
   ("And notice, the product was never boring. It was simply the star of a story worth watching.", 3)]),
 dict(title="Sell the Experience, Not Yourself", layout="compare",
  items=["\"We are the best blender.\"|Talks about you", "\"Imagine what you could blend.\"|Talks about them"],
  sents=[
   ("Another of Jonah's rules. Your ad should never be only about you.", 0),
   ("Many companies fill their ads with features and bragging. We are the best. We are number one.", 1),
   ("But customers care about their own world, their own feelings, and their own stories.", 1),
   ("So instead of saying, we are the best blender, show how the product changes something in their life.", 2),
   ("This is Practical Value and Stories working together. Customers should feel like the hero, with your product in a helpful supporting role.", 2)]),
 dict(title="Potato Chips, Like a Designer Bag", layout="bullets",
  items=["Premium packaging, premium price", "Owning it feels like a status symbol", "Talking about it feels special"],
  sents=[
   ("Here is a surprising idea from the episode. Selling potato chips the way a luxury brand sells a handbag.", 0),
   ("Imagine elegant packaging, a higher price, and a feeling of exclusivity.", 1),
   ("Suddenly, a snack is no longer just a snack. It becomes a small status symbol.", 2),
   ("That is Social Currency again. People enjoy owning something that signals taste, and they enjoy telling others about it.", 3),
   ("The lesson is that a mundane product can be reframed. What you sell may be the same. How people feel about owning it can change completely.", 3)]),
 dict(title="Broken Patterns Grab Attention", layout="bullets",
  items=["Brains ignore predictable patterns", "Something odd breaks the pattern", "Attention first, then conversation"],
  sents=[
   ("Our brains are built to ignore the predictable.", 1),
   ("Every day we scroll past the same kinds of ads, and our minds filter them out automatically.", 1),
   ("But when something breaks the pattern, we notice.", 2),
   ("The episode points to a deliberately ugly ad that got people talking, and reportedly lifted sales sharply.", 2),
   ("Being unusual works because it earns attention first, and attention is the doorway to conversation.", 3),
   ("The trick is that the surprise has to fit the product. Random weirdness is just noise.", 3)]),
 dict(title="Don't Chase Virality", layout="hero",
  items=["Engineer it. Don't announce it.", "Triggers + value + story"],
  sents=[
   ("Here is the irony. Trying too hard to go viral often backfires.", 0),
   ("Audiences can smell a campaign that was built to be shared. It feels forced.", 1),
   ("Real sharing feels organic. So instead of chasing views, focus on triggers, on value, and on a story people want to tell.", 2),
   ("Let the sharing happen as a side effect.", 2)]),
 dict(title="Own a Trigger for Almost $0", layout="bullets",
  items=["Chai time + biscuit = sticky habit", "A day of the week can be a trigger", "Everyday routines are free reminders"],
  sents=[
   ("The cheapest trigger is the one that already exists in people's lives.", 0),
   ("Take tea time. In many homes, chai and biscuits go together every afternoon.", 1),
   ("A biscuit brand that links itself to that routine gets reminded to the customer every single day, without paying for another ad.", 1),
   ("Or take a day of the week. A campaign tied to one specific day can turn that day into a trigger, so each time it comes around, people think of the brand.", 2),
   ("The same holds for water, or any boring product. Find the daily habit, the health goal, or the status angle, and attach yourself to it.", 3),
   ("It costs very little, and it works every day.", 3)]),
 dict(title="Sell a Pen Without Mentioning the Pen", layout="bullets",
  items=["Sell confidence, achievement and ideas", "Let people tell their own story", "It is about them, not you"],
  sents=[
   ("Jonah ends with a classic challenge. Can you make someone want a pen, without ever talking about the pen?", 0),
   ("The answer is yes, if you sell what the pen helps people do.", 1),
   ("Confidence in a meeting. The first draft of a big idea. The signature on something important.", 1),
   ("When people can picture their own story, they start telling it to others, and that is where word of mouth begins.", 2),
   ("In short, it is not the product you are selling. It is how people see themselves using it.", 3)]),
 dict(title="Key Takeaway", layout="hero",
  items=["Virality = Science, Not Luck", "Social Currency  |  Triggers  |  Emotion  |  Public  |  Practical Value  |  Stories"],
  sents=[
   ("So, can a boring product go viral? Yes, if you stop hoping for luck and start using psychology.", 0),
   ("Make people look good. Connect to cues they meet every day. Spark a feeling. Make the product visible. Be useful. And wrap it all in a story.", 2),
   ("Next time you plan a campaign, remember. Virality is not a lottery. It is a strategy.", 1),
   ("Thanks for watching. Based on Jonah Berger's work, and the Indian Business Podcast.", 2)]),
]
